name: us-images-test
suffix: ~  # add suffix to saved images
model: blind
distortion: sr
scale: 4 # 2
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [0]

datasets:
  test:
    name: us-images
    mode: LQGT
    dataroot_GT: /opt/data/us_data/us_test/us_images_sig2/HR.lmdb
    dataroot_LQ: /opt/data/us_data/us_test/us_images_sig3/LRblur.lmdb


#### network structures
network_G:
  which_model_G: PRLMU
  setting:
    in_nc: 3


#### path
path:
  pretrain_model_G: /home/customer/ljy/PycharmProject/cascade_github/33_G.pth